"""modify role column in USER TABLE

Revision ID: a50492393b64
Revises: aa6311849230
Create Date: 2025-05-04 17:59:20.237599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a50492393b64'
down_revision: Union[str, None] = 'aa6311849230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'USER', 'EMPLOYER', name='user_roles'),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=postgresql.ENUM('ADMIN', 'USER', 'EMPLOYER', name='user_roles'),
               nullable=True)
    # ### end Alembic commands ###
