"""initial commit

Revision ID: a5276826502c
Revises: 
Create Date: 2025-04-18 16:13:40.522590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5276826502c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', 'EMPLOYER', name='user_roles'), nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'user_name')
    op.drop_column('users', 'date_joined')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'role')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
